-- MySQL Script generated by MySQL Workbench
-- Mon Jan 28 09:23:38 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `anyun` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `anyun` DEFAULT CHARACTER SET utf8 ;
USE `anyun` ;

-- -----------------------------------------------------
-- Table `mydb`.`m_platform`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `anyun`.`m_platform` ;

CREATE TABLE IF NOT EXISTS `anyun`.`m_platform` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `sn` VARCHAR(30) NOT NULL COMMENT '平台编号',
  `name` VARCHAR(30) NOT NULL COMMENT '平台名称',
  `type` VARCHAR(30) NOT NULL DEFAULT 'post' COMMENT '类型(post-发布/get-爬取)',
  `homeUrl` VARCHAR(100) NOT NULL COMMENT '平台首页',
  `sdkClass` VARCHAR(30) NOT NULL COMMENT 'SDK类名',
  `isEnable` TINYINT(1) UNSIGNED NOT NULL COMMENT '是否可用',
  `createTIme` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updateTime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`m_platform_account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `anyun`.`m_platform_account` ;

CREATE TABLE IF NOT EXISTS `anyun`.`m_platform_account` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `platformSn` VARCHAR(30) NOT NULL COMMENT '平台编号',
  `platformName` VARCHAR(30) NOT NULL COMMENT '平台名称',
  `loginname` VARCHAR(30) NOT NULL COMMENT '登录名',
  `loginpass` VARCHAR(30) NOT NULL COMMENT '登录密码',
  `phoneNum` VARCHAR(11) NOT NULL COMMENT '手机号码',
  `isEnable` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否有效',
  `isPost` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否是发布账户',
  `score` INT(11) NOT NULL DEFAULT 0 COMMENT '积分',
  `loginStatus` VARCHAR(60) NOT NULL DEFAULT '' COMMENT '登录状态',
  `postUrl` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '发表博客URL',
  `loginType` VARCHAR(30) NOT NULL DEFAULT 'auto' COMMENT '登录方式（auto-自动/manual-手动）',
  `loginCookie` VARCHAR(2000) NOT NULL DEFAULT '' COMMENT '登录Cookie',
  `loginCookieEnable` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '登录Cookie是否有效',
  `loginCookieUpdateTime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '登录Cookie更新时间',
  `createTime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updateTime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`m_post_task`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `anyun`.`m_post_task` ;

CREATE TABLE IF NOT EXISTS `anyun`.`m_post_task` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NOT NULL COMMENT '标题',
  `selfCategory` VARCHAR(30) NULL,
  `tags` VARCHAR(30) NULL,
  `content` TEXT NOT NULL COMMENT '内容',
  `status` VARCHAR(30) NOT NULL DEFAULT 'init' COMMENT '状态(init-初始/processing-处理中/success-成功/fail-失败)',
  `planPostTime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '预定发布时间',
  `createTime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updateTime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '发布任务表';


-- -----------------------------------------------------
-- Table `mydb`.`m_post_task_platform`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `anyun`.`m_post_task_platform` ;

CREATE TABLE IF NOT EXISTS `anyun`.`m_post_task_platform` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `taskId` INT NOT NULL COMMENT '任务ID',
  `platformSn` VARCHAR(100) NOT NULL COMMENT '平台编号',
  `accountId` INT NOT NULL COMMENT '账户ID',
  `status` VARCHAR(30) NOT NULL DEFAULT 'init' COMMENT '状态(init-初始/processing-处理中/success-成功/fail-失败)',
  `detailUrl` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '详情页URL',
  `viewCount` INT NOT NULL DEFAULT 0 COMMENT '浏览数量',
  `lastViewTime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后浏览时间',
  `refUrl`  VARCHAR(100) NOT NULL DEFAULT '' COMMENT '转载URL',
  `createTime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updateTime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `mydb`.`m_scrapy_task`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `anyun`.`m_scrapy_task` ;

CREATE TABLE IF NOT EXISTS `anyun`.`m_scrapy_task` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `spiderName` VARCHAR(100) NOT NULL COMMENT '爬虫名称',
  `title` VARCHAR(100) NOT NULL COMMENT '标题',
  `sourceUrl` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '内容页URL',
  `sourceUrlHash` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '内容页URL的hash值（唯一）',
  `category` VARCHAR(60) NOT NULL DEFAULT '' COMMENT '分类',
  `tag` VARCHAR(60) NOT NULL DEFAULT '' COMMENT '标签',
  `publishDate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '发布日期',
  `distPlatformSn` VARCHAR(100) NOT NULL COMMENT '发布平台编号，多个编号使用逗号分隔(例：sinablog,cnblogs)',
  `status` VARCHAR(30) NOT NULL DEFAULT 'init' COMMENT '状态(init-初始/success-成功/fail-失败)',
  `createTime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updateTime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`m_scrapy_task`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `anyun`.`m_proxy_ip` ;

CREATE TABLE IF NOT EXISTS `anyun`.`m_proxy_ip` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `ip` varchar(100) COLLATE utf8mb4_general_ci NOT NULL COMMENT 'IP',
  `port` int(10) UNSIGNED NOT NULL COMMENT '端口',
  `ipHash` varchar(100) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT 'IP+port的hash值（唯一）',
  `protocol` varchar(5) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '协议类型（http/https)',
  `speed` decimal(6,4)  NOT NULL DEFAULT '0.00' COMMENT '响应时间',
  `last_checked_time` timestamp NOT NULL COMMENT '最后检查时间',
  `country` varchar(20) COLLATE utf8mb4_general_ci NOT NULL COMMENT '国家',
  `web_site` varchar(100) COLLATE utf8mb4_general_ci NOT NULL COMMENT '来源网站',
  `status` varchar(10) COLLATE utf8mb4_general_ci NOT NULL DEFAULT 'init' COMMENT '状态(init-初始/enable-有效/unenable-无效)',
  `invalidNum` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '无效次数',
  `createTime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updateTime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `ipHash_UNIQUE` (`ipHash`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
